Добавлен ноутбук с практическим заданием №3.
dgrandis/python_for_data_analysis pull request #2
Opened 2024-03-09 11:25 UTC by dgrandis

Практическое_задание_3.ipynb
train.csv
README файл

2024-03-10 20:54 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу! Все отлично!

2024-03-10 20:57 UTC, dgrandis commented
Спасибо большое 🙂

2024-03-10 20:57 UTC, merged

2024-03-10 21:00 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! В целом все отлично!

Упомяну, что процент выживаемости пассажиров можно чуть лаконичнее посчитать как-нибудь так: `df.groupby('Pclass')['Survived'].mean() * 100`

А в последнем задании "Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека)" предполагался формат вывода "2 - 300, 3 - 400" то есть количество человек в двуместной, трехместной и других кабинах

2024-03-11 10:14 UTC, dgrandis commented
Добрый день, Кристина. Спасибо за обратную связь. Действительно процент
выживаемости так действительно более понятнее и лаконичнее. Спасибо за
совет. В последнем задании про вывод понял, учту)

пн, 11 мар. 2024 г. в 00:00, pacifikus ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Добрый день!
>
> Спасибо за работу! В целом все отлично!
>
> Упомяну, что процент выживаемости пассажиров можно чуть лаконичнее
> посчитать как-нибудь так: df.groupby('Pclass')['Survived'].mean() * 100
>
> А в последнем задании "Выведите количества n-местных кабин (в которых было
> 2, 3, 4, ... человека)" предполагался формат вывода "2 - 300, 3 - 400" то
> есть количество человек в двуместной, трехместной и других кабинах
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dgrandis/python_for_data_analysis/pull/2#pullrequestreview-1926697688>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APRNLUFMDD5TZPX3XI677N3YXTCYNAVCNFSM6AAAAABEOBCCHSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMRWGY4TONRYHA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> com>
>